"""Creacion tabla orders

Revision ID: e952dcd86a0c
Revises:
Create Date: 2026-09-28 16:31:48.177276

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e952dcd86a0c"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orders",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("cliente_id", sa.Integer(), nullable=False),
        sa.Column("producto", sa.String(length=100), nullable=False),
        sa.Column("precio", sa.Float(), nullable=False),
        sa.Column("cantidad", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("orders")
    # ### end Alembic commands ###
